language: node_js
node_js:
- 6.9.4
install:
- npm install
cache:
  directories:
  - node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: goldenboy-bot
  api_key:
    secure: SuBWHr0ds+lWSpd2xuSXXoAH5sejfWH5dh5oG3hJJSi/SCf28v/YutnIZGz0fgbEhniXQJ3vH6nwIX58hn43/qN4/OYHDVioiJhxwa5yQ3lbvh1Co6GNsHkjUZ4zUPXBqYNymfaLmB6pku1ej67FVzQIgryqJ5RzzYEZzp5j6Jryw4Y7BSbYIdFCdkLMj7Ey3DD/9VVTSLax2nKUQlGnCS4OYUY0nc6lzqMcQJe27VaAZ3S136M+KlJu5CpH6SrYaJEHECUkYY/hVL9LTFsz/J2+LKG8ab59xZ/+n1NqYetbMkpheS5faM+zr8P/SnPdFcIR+8kd9HWxHv+CO7MdRmCor8RSebttX3NJh3z9mx1s1+L6EjQBvyexPlrLBXKuG4hDnmrB9eYoeoj+CfVFmTAVjT01XV5CjHs1Wrb2WKfk6KI8pyPS38ti49iK/pIRsmAXaD+DBQmkKPsKAlLUKO4PyYbYfE1uTMLnZYHgZ3+2KGr54emuhbzujYmJMPVNCiBBU5pXrMAt2blvBWdLLGFsRzzy/CKDaLka1tpppxgmUP1vC2gsaxu2jVCRqrylIENiuLKWimIXkgTjW2u77COeR529CIOEWIjpiV8cvNyOTS59G5lzSXMcTbZnrQh3c0t3ebjXxCt0eTu7yA9a8PzZvblJs6yfJfpgEtOn4cM=
  on:
    repo: codehangar/goldenboy-bot
    branch: master
notifications:
  slack:
    secure: zDEkAEgThuNCUGPy7qR0FEqEH4wDec7XHM7zI5KDaIeZ2JzIphn8E34nZcvm4V/tEio5H+/iZON3knevh95D9HJRRZC1hGFHkW0G+eo1I8Hkc6ULKgAQR6x6ta9/dt/3xItQXW/Z/zsFYlevMaveo7ERdTBOiWI5eBP2py+d3a1xxZuC2wLuWfUkBLnkOxo9EFGxkzAaU2zTzlKbW2Dgyx1MQ0ULYxTithoOWDRkr78kbppf+jwKUO0z0CjThoQVbOO7MFYieoW1Z3cNciO+tdUHexqCDQrtU3216cdkHt3t51YO9fVKRINUPV1fwg7m+fTwSM0uNyRb+xqzAOw+QNnsxPYaPCrSGI1qDt67mW3pUwYp0avWWt7REqq6AtPzcQ8Q/U4EEma5+rYHrXvOX3CtNMcCfo+gQHu9dWJT7X8VzESxBIloPchR6yT6IxPOz8pPd2npVCtDzjKXj8QOE+7O64etKqwktL/Oby9ItZn42wEnltgsJSEmf4TZ2U8Wyhn0DPl1fdYAzSq3Qp2CtRQgsw/72u3MAbnM41LFzH19HH7dZL6g/uVHNyIz9b1qwT3/iKDXCZhXt8EroP75abZxbl//vdVMvifO7A1HLnDA/4vuLLxHwC881C/shFnlwX493w/4bH/Hv98gC0wLvcS+ACYncqxab12Abiq4dPg=
